version: '3.8'
services:
  dt_app:
      container_name: dt_app
      build:
        context: .
        dockerfile: ./Dockerfile
      command: uvicorn main:app --host 0.0.0.0 --port 8010
      ports:
        - 8010:8010
      volumes:
        - ./api/:/app/
        - ./api/devices.json:/app/devices.json
      environment:
        - TZ=Europe/Paris
      networks:
        - db_network

networks:
  db_network:
    driver: bridge